SET FOREIGN_KEY_CHECKS = 0;
DROP table if exists Operating_Times;
DROP table if exists Folk_email;
DROP table if exists Lives;
DROP table if exists Registers;
DROP table if exists Administrators;
DROP table if exists Judges;
DROP table if exists Clerks;
DROP table if exists Cast_Votes;
DROP table if exists Monitors;
DROP table if exists Works_at;
DROP table if exists Election_Staff;
DROP table if exists Folks;
DROP table if exists Residences;
DROP table if exists Offers;
DROP table if exists Voting_Centers;
DROP table if exists Places;
DROP table if exists Ballots;
SET FOREIGN_KEY_CHECKS = 1;
